sudo: false
os:
  - linux
language: node_js
node_js:
  - "0.10"
  - "0.11"
  - "0.12"
  - "4"
  - "5"
  - "6"
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - clang-3.5
      - g++-4.8
env:
  matrix:
    - CXX=g++-4.8 TEST_SUITE=unit:node
matrix:
  include:
    - os: linux
      node_js: "4"
      env: CXX=g++-4.8 TEST_SUITE=lint
    - os: linux
      node_js: "4"
      env: CXX=clang++ TEST_SUITE=unit
script: npm run $TEST_SUITE
